DBCDK/dk5

src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/state/client.js
src/client/state/state.js
src/client/state/stateWrapper.component.js
src/components/ElasticSearch/ElasticSearchClass.js

load hierarchy from api

---

README.md
src/components/ElasticSearch/ElasticSearch.util.js
src/components/ElasticSearch/ElasticSearchClass.js
src/iso2709ToElasticLoad

and fix. search to include top groups

#66: charmap : (colon). Add general note (from b00)

---

postcss.config.js
src/client/components/General/spinner.component.js
src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/components/SearchField/SearchField.component.js
src/client/components/SearchResultsContainer/SearchResultsContainer.component.js
src/client/scss/components/Hierarchy.scss
src/client/scss/components/SearchField.component.scss
src/client/scss/components/SearchResultsContainer.component.scss
src/client/scss/includes/spinner.scss
webpack.config.js

Der skal være en indikator der viser at der foretages kald til API

---

integration/tests/hierarchy.test.js
package.json
src/client/components/General/toggle.component.js
src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/scss/components/HelpContainer.component.scss
src/client/scss/components/Hierarchy.scss

Ved lange lister i hierarkiet vises de 5 første med mulighed for at folde de resterende ud.

---

src/client/components/General/toggle.component.js
src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/components/SearchField/SearchField.component.js
src/client/scss/components/Hierarchy.scss
src/client/scss/components/SearchField.component.scss
src/client/scss/components/TopBar.component.scss
src/client/scss/globals/typography.scss
src/client/scss/includes/media-quires.scss
src/client/scss/index.scss
src/components/ElasticSearch/ElasticSearchClass.js

Responsiv visning af hierarkiet

---

src/client/scss/components/Hierarchy.scss
src/client/scss/components/SearchField.component.scss
src/client/scss/components/SearchResultsContainer.component.scss

Forsiden skal justeres på mobil/tablet

---

src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/scss/components/Hierarchy.scss

På mobil skal man på forsiden frem for til hierakiet hvis man er på øverste niveau - fx. 00-07

---

src/client/components/SearchField/SearchField.component.js

Søgning og brug af suggestion funker ikke når man bruger mus

---

src/client/components/SearchResultsContainer/SearchResultsContainer.component.js

State opdateres ikke ved brug af autocomplete gentagne gange

---

.gitignore
integration/tests/cart.mobile.test.js
integration/tests/cart.test.js
integration/tests/navbar.test.js
src/app.js
src/client/components/Cart/CartButton.component.js
src/client/components/Cart/TopbarCart.component.js
src/client/components/Cart/TopbarCartItem.component.js
src/client/components/Comparer/ComparerContainer.component.js
src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/components/RootContainer/RootContainer.component.js
src/client/components/TopBar/TopBar.component.js
src/client/scss/components/CartButton.component.scss
src/client/scss/components/ComparerContainer.component.scss
src/client/scss/components/Hierarchy.scss
src/client/scss/components/TopBar.component.scss
src/client/scss/globals/globals.scss
src/client/scss/includes/media-quires.scss
src/client/scss/includes/transitions.scss
src/client/scss/index.scss
src/client/state/client.js
src/routes/index.routes.js

Det skal laves en visning til at sammenligne poster

---

package.json

Addressing Greenkeeper issues

---

integration/tests/searchresults.pro.test.js
integration/tests/searchresults.test.js
package.json
src/client/components/Cart/CartButton.component.js
src/client/components/SearchField/SearchField.component.js
src/client/components/SearchResultsContainer/SearchResultsContainer.component.js
src/client/scss/components/Hierarchy.scss
src/client/scss/components/SearchField.component.scss
src/client/scss/components/SearchResultsContainer.component.scss

Visning af sammenligner på søgeresultatsside mm.

---

src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/components/RootContainer/RootContainer.component.js
src/client/scss/components/ComparerContainer.component.scss
src/client/scss/components/Hierarchy.scss
src/client/scss/globals/resets.scss
src/client/scss/index.scss

PRO: Scroll af venstre side

---

integration/tests/hierarchy.mobile.test.js
src/app.js
src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/components/ElasticSearch/__mocks__/list.mock.json
src/routes/api.routes.js

Navigation via navbar på mobil skal fikses

---

src/client/components/SearchResultsContainer/SearchResultsContainer.component.js
src/client/scss/components/SearchResultsContainer.component.scss
src/client/scss/index.scss
src/components/ElasticSearch/ElasticSearch.util.js
webpack.config.js

Responsivt søgeresultat

---

CHANGELOG.md
README.md

Udviklerdokumentation

---

CHANGELOG.md
integration/tests/resetToFrontpage.test.js
src/app.js
src/client/components/ResetToFrontpage/ResetToFrontpage.component.js
src/client/components/RootContainer/RootContainer.component.js
src/client/scss/components/ResetToFrontpage.component.scss
src/client/scss/index.scss
src/routes/index.routes.js

Automatisk nulstilling til forside

---

src/client/scss/components/CartButton.component.scss

Fix line-height in pro edition

---

src/client/components/RootContainer/RootContainer.component.js
src/client/scss/components/ComparerContainer.component.scss
src/client/scss/components/Hierarchy.scss

Bring back second scrollbar

---

src/components/ElasticSearch/ElasticSearch.util.js
src/components/ElasticSearch/ElasticSearchClass.js
src/components/ElasticSearch/__tests__/ElasticSearch.util.test.js

Match on search query

---

src/client/components/SearchResultsContainer/SearchResultsContainer.component.js
src/components/ElasticSearch/ElasticSearch.util.js
src/components/ElasticSearch/ElasticSearchClass.js
src/components/ElasticSearch/__tests__/ElasticSearch.util.test.js

Show all register words

---

src/components/ElasticSearch/ElasticSearch.util.js
src/components/ElasticSearch/ElasticSearchClass.js
src/components/ElasticSearch/__tests__/ElasticSearch.util.test.js

Sort by title instead of index.

---

integration/tests/searchresults.pro.test.js
src/client/components/SearchResultsContainer/SearchResultsContainer.component.js
src/components/ElasticSearch/ElasticSearch.util.js
src/components/ElasticSearch/__tests__/ElasticSearch.util.test.js

Add historical note on register posts and words

---

src/client/components/Link/index.js
src/client/components/SearchResultsContainer/SearchResultsContainer.component.js

Use link component to trigger redirects

---

integration/tests/cart.test.js
integration/tests/hierarchy.test.js
integration/tests/searchField.test.js
integration/utils/browser.util.js
src/client/components/HelpContainer/HelpContainer.component.js
src/client/components/RootContainer/RootContainer.component.js
src/client/components/Suggestions/Suggestions.component.js
src/client/components/TopBar/TopBar.component.js

Change a tags to Link tags

---

integration/tests/hierarchy.test.js
src/client/components/ResetToFrontpage/ResetToFrontpage.component.js
src/client/components/RootContainer/RootContainer.component.js
src/client/components/SearchField/SearchField.component.js

Inputfield reset bug + autofocus searchfield on new search

---

package-lock.json
src/client/components/SearchField/SearchField.component.js
src/client/components/SearchResultsContainer/SearchResultsContainer.component.js
src/components/ElasticSearch/ElasticSearch.util.js
src/components/ElasticSearch/ElasticSearchClass.js
src/components/ElasticSearch/index.js
src/routes/api.routes.js

#586 
Løser: 
- Bedre forslag ved 0 hit søgning 
Der er tilføjer et merged array til responset ved en søgning, merged arrayet består af de mest relevante resultater fra både prefix og spell arrayet. 
- Bedre "Din-søgning-gav-ikke-nogle-resultater-vi-har-i-stedet-søgt-på" ord
- Løser infinite spinner bug ved "Hvis-du-vil-prøve-din-søgning-alligevel-klik-her!" knap

586 0 hit suggest

---

src/client/components/ResetToFrontpage/ResetToFrontpage.component.js
src/client/components/SearchField/SearchField.component.js

Løser IE bugs på issue #588 #265

fixes input bugs in IE

---

src/client/components/ResetToFrontpage/ResetToFrontpage.component.js
src/client/components/RootContainer/RootContainer.component.js
src/client/components/SearchField/SearchField.component.js

løser issue: #577
- Ændret "popstate" eventListener til "hashChange", da denne understøttes i både IE11 og de andre øvrige browsere. 
- BackButton tvinges til at virke med en location.href

577 forward back button

---

.babelrc
integration/config/sauce.conf.js
integration/config/wdio.conf.js
integration/tests/resetToFrontpage.test.js
package-lock.json
package.json
src/main.js
webpack.config.js

Update babel setup to handle IE11

---

src/client/scss/components/Hierarchy.scss
src/client/scss/components/SearchField.component.scss
src/client/scss/components/SearchResultsContainer.component.scss
src/client/scss/config/config.scss

Last adjustments for [TAN-663]
[TAN-663]: https://dbcjira.atlassian.net/browse/TAN-663

Color and outline adjustments

---

src/client/components/SearchResultsContainer/SearchResultsContainer.component.js
src/client/scss/components/SearchField.component.scss

Part of [TAN-663]
[TAN-663]: https://dbcjira.atlassian.net/browse/TAN-663

Fix input in safari + link title

---

src/client/components/Cart/CartButton.component.js
src/client/components/HierarchyContainer/HierarchyContainer.component.js
src/client/components/svg/svg.container.js
src/client/scss/components/Hierarchy.scss

styled decommisioned groups and fixed links

---

src/client/components/HelpContainer/HelpContainer.component.js

corrections in help text

---

pipelines/dump/Dockerfile
pipelines/dump/Jenkinsfile

Denne merge handler kun om at lave et dockerimage som kan dumpe tanterne i libv3-miljøet, og sende det til artifactory

653 move dk5 to k8s

---

pipelines/build-dk5-image/Jenkinsfile
pipelines/build-libv3-image/Jenkinsfile
pipelines/load-data-in-dk5/Dockerfile
pipelines/load-data-in-dk5/Jenkinsfile

Ny Jenkinsfile til dataload flow, samt en rettelse i en anden Jenkinsfile der manglede at rydde op efter sig.

685 load data i dk5

---

src/client/components/RootContainer/RootContainer.component.js
src/client/scss/index.scss

Solves [TAN-695]
[TAN-695]: https://dbcjira.atlassian.net/browse/TAN-695

Add accessibility link
